name: mojolo
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '2.19.6'
  
dependencies:
  flutter:
    sdk: flutter
  sliding_up_panel: ^2.0.0+1
  toggle_switch: ^2.1.0
  appinio_swiper: ^2.0.0
  glass_container: ^0.0.2
  cupertino_icons: ^1.0.2
  swipeable_card_stack: ^0.0.5
  swipe_deck: ^1.1.0
  google_fonts: ^4.0.3
  curved_navigation_bar: ^1.0.3
  flutter_neumorphic: ^3.2.0
  card_swiper: ^2.0.4
  chatview: ^1.2.1
  counter_button: ^1.0.1
  card_stack_widget: ^0.1.3
  another_xlider: ^3.0.1
  syncfusion_flutter_sliders: ^21.1.39
  bubble: ^1.2.1
  bulleted_list: ^0.0.1+0.1a
  avatar_glow: ^3.0.1

  quickalert: ^1.0.1
  file_picker: ^5.2.5
  image_picker: ^0.8.6+1
  mime: ^1.0.4
  open_filex: ^4.3.2
  uuid: ^3.0.7
  flutter_chat_ui: ^0.0.2
  permission_handler: ^10.2.0
  flutter_chat_types: ^3.6.0
  carousel_slider: ^4.2.1
 
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

 
  assets:
  - assets/
  - assets/icons/
  - assets/icons/tickets.png
 